### ISSUE TITLE
Subscriber in matlab not returning data values

### ISSUE THREAD

**Issue by mrahsanahmad** [BrendanAndrade/web-matlab-bridge#2]
I am using Ubuntu 64 bit , Matlab 2012(a), JAVA 1.7_0.25, MATLAB_JAVA = JAVA 1.7_0.25, used ant to rebuild the src files, added the java_websocket.jar to static class path,

when running example.m, I get the Exception
java.lang.NullPointerException
    at com.mathworks.jmi.bean.MatlabBeanInterface.addCallback(MatlabBeanInterface.java:765)
    at com.mathworks.jmi.bean.MatlabCallbackInterface.addCallback(MatlabCallbackInterface.java:130)

It is occuring at the line where publisher is initialzed

Main problem --> subscriber.data is empty ... it is not returning any data

**Comment by BrendanAndrade** [comment]
Do you have the rosbridge_server node running? http://www.ros.org/wiki/rosbridge_server

Also, this package is still very much in development.

**Comment by mrahsanahmad** [comment]
Yes, I do have rosbridge_server node running, otherwise I couldnt have been able to to publish data from matalb to ROS. I can publish the data but cannot subscribe to it. I think it has to do with callback function because thats what I was getting in error. 

I understand that the package is in development and do appreciate your efforts. Currently I am writing my master thesis on ROS-NAOqi-MATLAB integration and if there is someway i can be of your help, please let me know.

 
Thank you and Regards

Ahsan Ahmad Yousuf

**Comment by BrendanAndrade** [comment]
If you have a rosbridge_server node running and run the script example.m, does that yield an error?

**Comment by mrahsanahmad** [comment]
Sounds wierd, but after receiving your email, i decided to write you a detailed email. I wanted to have a look at the errors again but surprisingly, running example.m didnt give any errors this time and i was able to receive the message that was published. otherwise previously, i was only able to publish the messages and not receive them. I am sorry for the trouble.

 
Thank you and Regards

Ahsan Ahmad Yousuf

**Comment by BrendanAndrade** [comment]
If you're still having trouble with you're own code, please post the code or point me to the repo.

**Comment by mozcelikors** [comment]
I have the same issue. The subscriber example does work. But it doesnt work with a std_msgs/String type topic.
