### ISSUE TITLE
No class org.java_websocket.bridge.ROSBridgeClient can be located on Java class path

### ISSUE THREAD

**Issue by mingot** [BrendanAndrade/web-matlab-bridge#3]
It seems like ros_websocket.m can not load the Java object. Do I have to do anything special to let Matlab know where is the java_websocket located?

Thanks!

The full error output:

```
??? Undefined function or method 'ROSBridgeClient' for input arguments of type 'java.net.URI'.

Error in ==> ros_websocket>ros_websocket.ros_websocket at 82
        obj.client = ROSBridgeClient(obj.MASTER_URI);

Error in ==> example at 37
ws = ros_websocket(master_uri);
```

**Comment by mingot** [comment]
I was importing (via javaadpath) the official java_websocket.jar instead of using the one that you provide. The original does not have the ROSBridgeClient.

**Comment by BrendanAndrade** [comment]
This project is still under development. It's meant bridge to Robotic Operating System (ROS) through rosbridge 2.0. There are still a few bugs and performance issues.

The .jar file should be added to the static class path for everything to work properly. javaaddpath adds to the dynamic class path. You must add to the static class path by editing the classpath.txt file. I hope to have this done automatically in the future but have not implemented it yet.
